services:
  wordpress-db:
    container_name: wordpress-db
    image: mariadb:10.6.4-focal
    # command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
      - 33060
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - ./wp_data:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
    ports:
      - 8000:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_NAME=${DB_DATABASE}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - wordpress-db

volumes:
  db_data: